### ISSUE TITLE
Es fehlen ganz viele translation texte

### ISSUE THREAD

**Issue by rubo77** [freifunk-nordheide/ffnordheide#3]
Wenn die fehlen, dann steht dort im config mode immer nur der platzhalterstring.

du kannst die texte aus der kieler Firmware übernehmen: 

https://github.com/freifunk-kiel/site-ffki/blob/master/i18n/de.po

nur den satz "Bitte meldet mich beim Knotenformular an" könnte raus

**Comment by Tarnatos** [comment]
fixed:
https://github.com/freifunk-nordheide/ffnordheide/commit/f583d1d5ebef084144bc517a4cb7bb27bb2da480
